project_id = "afjvxjvmtzzybujtwtxj"

[functions.generate-code]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.visual-edits]
verify_jwt = false

[functions.vercel-deploy]
verify_jwt = false

[functions.modal-proxy]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.supabase-oauth]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false
