project_id = "afjvxjvmtzzybujtwtxj"

[functions.generate-code]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.visual-edits]
verify_jwt = false

[functions.vercel-oauth]
verify_jwt = false

[functions.vivora-deploy]
verify_jwt = false

[functions.vercel-deploy]
verify_jwt = false

[functions.background-generate]
verify_jwt = false

[functions.screenshot-test]
verify_jwt = false