/**
 * THESIS: A merchandising desk, not a generic analytics dashboard.
 * OWN-WORLD: Vivora ink workspace, quiet dividers, pink commands, and a customer-store preview as the dominant artifact.
 * STORY: The owner sees the live shop, tends the catalog, moves orders, and directs the identity without technical language.
 * FIRST VIEWPORT: Task rail, store status bar, live storefront viewport, and a narrow today queue.
 * FORM: Storefront Studio, candidate four in the established Vivora X world; seed 204fe6c1.
 */
import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Box, Check, ExternalLink, Eye, LayoutDashboard, Menu, PackagePlus, Palette, RefreshCw, Save, ShoppingBag, SlidersHorizontal, Trash2, Truck, X } from 'lucide-react';
import { VivoraLogo } from '@/components/shared/VivoraLogo';
import { useAuth } from '@/contexts/AuthContext';
import { storeApi } from '@/services/storeService';
import type { Store, StoreOrder, StoreProduct } from '@/types/store';
import { toast } from '@/hooks/use-toast';
import './StoreAdmin.css';

type Tab = 'overview' | 'products' | 'orders' | 'identity';
const tabs: Array<[Tab,string,typeof LayoutDashboard]> = [['overview','اليوم',LayoutDashboard],['products','المنتجات',Box],['orders','الطلبات',ShoppingBag],['identity','الهوية',Palette]];
const orderLabels: Record<StoreOrder['status'],string> = { new:'جديد',confirmed:'مؤكد',preparing:'قيد التجهيز',shipped:'خرج للشحن',delivered:'تم التوصيل',cancelled:'ملغي' };

export default function StoreAdmin() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { user, loading:authLoading } = useAuth();
  const [store,setStore]=useState<Store|null>(null); const [tab,setTab]=useState<Tab>('overview'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [mobileNav,setMobileNav]=useState(false);
  const load=useCallback(async()=>{try{setLoading(true);setStore(await storeApi.get(id));setError('');}catch(err){setError((err as Error).message);}finally{setLoading(false);}},[id]);
  useEffect(()=>{if(user)void load();},[user,load]);
  if(authLoading||loading)return <StudioState text="بنفتح استوديو المتجر…"/>;
  if(!user)return <StudioState text="سجّل الدخول لإدارة متجرك." action={<button onClick={()=>navigate('/login')}>تسجيل الدخول</button>}/>;
  if(error||!store)return <StudioState text={error||'المتجر غير موجود.'} action={<button onClick={()=>navigate('/')}>الصفحة الرئيسية</button>}/>;
  return <main className="store-studio" dir="rtl">
    <aside className={`store-studio-rail ${mobileNav?'is-open':''}`}><div className="store-studio-logo"><VivoraLogo size="sm"/><button onClick={()=>setMobileNav(false)}><X/></button></div><div className="store-rail-store"><span>{store.name.slice(0,1)}</span><div><strong>{store.name}</strong><small>{store.status==='published'?'متاح للطلب':'غير منشور'}</small></div></div><nav>{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setMobileNav(false)}}><Icon/><span>{label}</span></button>)}</nav><a className="store-rail-view" href={`/shop/${store.slug}`} target="_blank" rel="noreferrer"><Eye/>فتح المتجر<ExternalLink/></a><button className="store-rail-back" onClick={()=>navigate('/')}><ArrowLeft/>العودة إلى Vivora X</button></aside>
    {mobileNav&&<button className="store-mobile-backdrop" onClick={()=>setMobileNav(false)} aria-label="إغلاق القائمة"/>}
    <section className="store-studio-main"><header className="store-studio-top"><button className="store-menu-button" onClick={()=>setMobileNav(true)}><Menu/></button><div><p>{tabs.find(item=>item[0]===tab)?.[1]}</p><span><i/>كل التغييرات محفوظة</span></div><button onClick={()=>void load()}><RefreshCw/>تحديث</button></header><div className="store-studio-content">{tab==='overview'?<StoreOverview store={store}/>:tab==='products'?<ProductsWorkspace store={store} reload={load}/>:tab==='orders'?<OrdersWorkspace store={store} reload={load}/>:<IdentityWorkspace store={store} onSaved={updated=>setStore(current=>current?{...current,...updated,products:current.products,orders:current.orders}:updated)}/>}</div></section>
  </main>;
}

const StudioState=({text,action}:{text:string;action?:ReactNode})=><div className="store-studio-state"><VivoraLogo size="md"/><p>{text}</p>{action}</div>;

function StoreOverview({store}:{store:Store}){
  const orders=store.orders||[]; const products=store.products||[]; const revenue=orders.filter(item=>item.status!=='cancelled').reduce((sum,item)=>sum+item.total,0); const lowStock=products.filter(item=>item.stock<5).length;
  return <div><StudioHeading title={`صباح الخير، ${store.name}`} description="المتجر قدامك كما يراه العميل، والمهام التي تحتاج تدخلك بجانبه."/><div className="studio-overview"><section className="studio-live"><header><div><span className="studio-live-dot"/>معاينة مباشرة</div><a href={`/shop/${store.slug}`} target="_blank" rel="noreferrer">فتح بحجم كامل<ExternalLink/></a></header><iframe src={`/shop/${store.slug}`} title={`معاينة ${store.name}`}/></section><aside className="studio-today"><p className="studio-label">نبض المتجر</p><h2>المطلوب منك الآن</h2><div className="studio-signal-list"><div><span><ShoppingBag/></span><p>طلبات جديدة<strong>{orders.filter(item=>item.status==='new').length}</strong></p></div><div><span><Truck/></span><p>قيد التجهيز<strong>{orders.filter(item=>item.status==='preparing').length}</strong></p></div><div><span><Box/></span><p>مخزون منخفض<strong>{lowStock}</strong></p></div></div><div className="studio-revenue"><span>إجمالي الطلبات</span><strong>{new Intl.NumberFormat(store.config.locale,{style:'currency',currency:store.config.currency}).format(revenue)}</strong><small>من الطلبات غير الملغاة</small></div></aside></div></div>;
}

const StudioHeading=({title,description,action}:{title:string;description:string;action?:ReactNode})=><div className="studio-heading"><div><h1>{title}</h1><p>{description}</p></div>{action}</div>;

const blankProduct: Partial<StoreProduct>={name:'',description:'',price:0,compareAtPrice:null,stock:0,imageUrl:'',category:'General',status:'active',featured:false};
function ProductsWorkspace({store,reload}:{store:Store;reload:()=>Promise<void>}){
  const products=store.products||[]; const [selectedId,setSelectedId]=useState<string|null>(products[0]?.id||null); const selected=products.find(item=>item.id===selectedId); const [draft,setDraft]=useState<Partial<StoreProduct>>(selected||blankProduct); const [saving,setSaving]=useState(false); const [query,setQuery]=useState('');
  useEffect(()=>setDraft(selected||blankProduct),[selectedId,selected?.updatedAt]);
  const visible=products.filter(item=>`${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  const save=async()=>{if(!draft.name?.trim())return toast({title:'اكتب اسم المنتج',variant:'destructive'});setSaving(true);try{const payload={...draft,price:Number(draft.price||0),stock:Number(draft.stock||0),category:draft.category||'General',status:draft.status||'active',featured:Boolean(draft.featured)};if(selected)await storeApi.updateProduct(store.id,selected.id,payload);else await storeApi.createProduct(store.id,payload);await reload();toast({title:selected?'تم تحديث المنتج':'تمت إضافة المنتج'});}catch(err){toast({title:'تعذّر حفظ المنتج',description:(err as Error).message,variant:'destructive'});}finally{setSaving(false);}};
  return <div><StudioHeading title="الكتالوج" description="قائمة المنتجات في ناحية، ومساحة تعديل مركزة في الناحية الثانية." action={<button className="studio-primary" onClick={()=>{setSelectedId(null);setDraft(blankProduct)}}><PackagePlus/>منتج جديد</button>}/><div className="studio-master-detail"><section className="studio-product-list"><label className="studio-search"><SlidersHorizontal/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث في المنتجات…"/></label><div>{visible.map(product=><button key={product.id} className={selectedId===product.id?'active':''} onClick={()=>setSelectedId(product.id)}><span className="studio-product-thumb">{product.imageUrl?<img src={product.imageUrl} alt=""/>:product.name.slice(0,1)}</span><span><strong>{product.name}</strong><small>{product.category} · {product.stock} متاح</small></span><b>{product.price.toLocaleString()} {store.config.currency}</b></button>)}</div></section><ProductEditor draft={draft} setDraft={setDraft} saving={saving} isExisting={Boolean(selected)} onSave={save} onDelete={selected?async()=>{if(!confirm('حذف المنتج نهائيًا؟'))return;await storeApi.deleteProduct(store.id,selected.id);setSelectedId(null);await reload();}:undefined}/></div></div>;
}
function ProductEditor({draft,setDraft,saving,isExisting,onSave,onDelete}:{draft:Partial<StoreProduct>;setDraft:(value:Partial<StoreProduct>)=>void;saving:boolean;isExisting:boolean;onSave:()=>void;onDelete?:()=>void}){const field=(key:keyof StoreProduct,value:unknown)=>setDraft({...draft,[key]:value});return <section className="studio-editor"><header><div><p>{isExisting?'تعديل المنتج':'منتج جديد'}</p><h2>{draft.name||'منتج بدون اسم'}</h2></div>{onDelete&&<button className="studio-danger" onClick={onDelete}><Trash2/>حذف</button>}</header><div className="studio-form-grid"><Field label="اسم المنتج" wide><input value={draft.name||''} onChange={e=>field('name',e.target.value)}/></Field><Field label="الوصف" wide><textarea value={draft.description||''} onChange={e=>field('description',e.target.value)}/></Field><Field label="السعر"><input type="number" min="0" value={draft.price||0} onChange={e=>field('price',Number(e.target.value))}/></Field><Field label="السعر قبل الخصم"><input type="number" min="0" value={draft.compareAtPrice||''} onChange={e=>field('compareAtPrice',e.target.value?Number(e.target.value):null)}/></Field><Field label="المخزون"><input type="number" min="0" value={draft.stock||0} onChange={e=>field('stock',Number(e.target.value))}/></Field><Field label="التصنيف"><input value={draft.category||''} onChange={e=>field('category',e.target.value)}/></Field><Field label="رابط الصورة" wide><input dir="ltr" value={draft.imageUrl||''} onChange={e=>field('imageUrl',e.target.value)}/></Field><Field label="الحالة"><select value={draft.status||'active'} onChange={e=>field('status',e.target.value)}><option value="active">منشور</option><option value="draft">مسودة</option><option value="archived">مؤرشف</option></select></Field><label className="studio-check"><input type="checkbox" checked={Boolean(draft.featured)} onChange={e=>field('featured',e.target.checked)}/><span><Check/>يظهر ضمن اختيارات المتجر</span></label></div><footer><span>المتجر يتحدث فور الحفظ</span><button onClick={onSave} disabled={saving}><Save/>{saving?'جارٍ الحفظ…':'حفظ المنتج'}</button></footer></section>}

const Field=({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean})=><label className={`studio-field ${wide?'wide':''}`}><span>{label}</span>{children}</label>;

function OrdersWorkspace({store,reload}:{store:Store;reload:()=>Promise<void>}){const orders=store.orders||[];return <div><StudioHeading title="غرفة الطلبات" description="حرّك الطلب من جديد إلى تم التوصيل، مع بيانات العميل واضحة في نفس الصف."/><section className="studio-orders"><header><span>الطلب والعميل</span><span>المكان</span><span>القيمة</span><span>الحالة</span></header>{orders.length?orders.map(order=><article key={order.id}><div><strong>{order.orderNumber}</strong><p>{order.customerName}</p><small>{order.phone}</small></div><div><p>{order.city}</p><small>{order.address}</small></div><strong>{order.total.toLocaleString()} {store.config.currency}</strong><select value={order.status} onChange={async e=>{await storeApi.updateOrder(store.id,order.id,e.target.value as StoreOrder['status']);await reload();}}>{Object.entries(orderLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></article>):<div className="studio-empty"><ShoppingBag/><h3>أول طلب هيظهر هنا</h3><p>افتح المتجر وجرّب رحلة الشراء كاملة.</p></div>}</section></div>}

function IdentityWorkspace({store,onSaved}:{store:Store;onSaved:(store:Store)=>void}){const [name,setName]=useState(store.name);const [config,setConfig]=useState(store.config);const [social,setSocial]=useState(store.social);const [saving,setSaving]=useState(false);const color=(key:keyof Store['config']['colors'],value:string)=>setConfig({...config,colors:{...config.colors,[key]:value}});return <div><StudioHeading title="المخرج الإبداعي" description="عدّل الحضور البصري والكلام والروابط؛ نظام البيع نفسه يفضل ثابت وآمن."/><div className="studio-identity"><section className="studio-identity-form"><div className="studio-form-section"><h2>العلامة</h2><Field label="اسم المتجر" wide><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="العنوان الرئيسي" wide><input value={config.hero.title} onChange={e=>setConfig({...config,hero:{...config.hero,title:e.target.value}})}/></Field><Field label="الوصف" wide><textarea value={config.hero.subtitle} onChange={e=>setConfig({...config,hero:{...config.hero,subtitle:e.target.value}})}/></Field><Field label="زر الدعوة"><input value={config.hero.cta} onChange={e=>setConfig({...config,hero:{...config.hero,cta:e.target.value}})}/></Field><Field label="شريط الإعلان"><input value={config.announcement} onChange={e=>setConfig({...config,announcement:e.target.value})}/></Field></div><div className="studio-form-section"><h2>نظام الألوان</h2><div className="studio-color-fields">{([['ink','الحبر'],['paper','الخلفية'],['accent','الإشارة'],['muted','النص الهادئ']] as const).map(([key,label])=><label key={key}><input type="color" value={config.colors[key]} onChange={e=>color(key,e.target.value)}/><span>{label}<b>{config.colors[key]}</b></span></label>)}</div></div><div className="studio-form-section"><h2>روابط التواصل</h2><Field label="Instagram" wide><input dir="ltr" value={social.instagram||''} onChange={e=>setSocial({...social,instagram:e.target.value})}/></Field><Field label="Facebook" wide><input dir="ltr" value={social.facebook||''} onChange={e=>setSocial({...social,facebook:e.target.value})}/></Field><Field label="WhatsApp" wide><input dir="ltr" value={social.whatsapp||''} onChange={e=>setSocial({...social,whatsapp:e.target.value})}/></Field></div><button className="studio-save-identity" disabled={saving} onClick={async()=>{setSaving(true);try{onSaved(await storeApi.update(store.id,{name,config,social}));toast({title:'تم تحديث هوية المتجر'});}catch(err){toast({title:'تعذّر حفظ الهوية',description:(err as Error).message,variant:'destructive'});}finally{setSaving(false);}}}><Save/>{saving?'جارٍ الحفظ…':'حفظ الهوية'}</button></section><aside className="studio-brand-proof" style={{'--proof-ink':config.colors.ink,'--proof-paper':config.colors.paper,'--proof-accent':config.colors.accent} as React.CSSProperties}><span>{config.announcement}</span><div><p>{name}</p><h2>{config.hero.title}</h2><p>{config.hero.subtitle}</p><button>{config.hero.cta}</button></div></aside></div></div>}
