export function getBoilerplateFiles() {
  return {
    "project/pages/index.html": `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Website</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>
    <main>
        <h1>Welcome to your new website!</h1>
        <p>This is a static site generated by Vibe.</p>
        <button id="click-me">Click Me</button>
    </main>
    <script src="../assets/js/main.js"></script>
</body>
</html>
`.trim(),
    "project/assets/css/style.css": `
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    line-height: 1.6;
    color: #333;
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
    background-color: #f4f4f9;
}

h1 {
    color: #2c3e50;
}

button {
    background-color: #3498db;
    color: white;
    border: none;
    padding: 10px 20px;
    font-size: 1rem;
    cursor: pointer;
    border-radius: 4px;
}

button:hover {
    background-color: #2980b9;
}
`.trim(),
    "project/assets/js/main.js": `
document.addEventListener('DOMContentLoaded', () => {
    const button = document.getElementById('click-me');
    if (button) {
        button.addEventListener('click', () => {
            alert('Hello! You clicked the button.');
        });
    }
});
`.trim(),
    "README.md": `
# Project Title

This is a static HTML/CSS/JS project.
`.trim()
  };
}
